// SPDX-License-Identifier: AGPL-3.0-or-later
// Copyright (C) 2025 Zeus <admin@brainode.com>

using System.Text;
using control_panel.Models;

namespace control_panel.Services;

public sealed class ReflexArenaGameAdapter : IGameAdapter
{
    public string GameKey => "reflex-arena";
    public string DisplayName => "Reflex Arena";
    public string ConfigurationPagePath => "/Configuration/ReflexArena";

    public GameSummary GetSummary(string? jsonSettings)
    {
        var settings = ReflexArenaConfigurationSerializer.Deserialize(jsonSettings);
        var selectedMutators = settings.Mutators
            .Select(mutator => ReflexArenaModuleCatalog.FindMutator(mutator)?.Label ?? mutator)
            .ToArray();
        var supportedMapsPreview = ReflexArenaModuleCatalog.GetSupportedMapsForMode(settings.Mode)
            .Take(6)
            .Select(ReflexArenaModuleCatalog.GetMapLabel)
            .ToArray();

        var limitsSummary = settings.TimeLimitOverride > 0
            ? $"Max {settings.MaxClients} players · {settings.TimeLimitOverride} min"
            : $"Max {settings.MaxClients} players";

        return new GameSummary(
            ModeName: ReflexArenaModuleCatalog.GetModeLabel(settings.Mode),
            ModeFlags: selectedMutators.Length == 0
                ? "Standard ruleset"
                : string.Join(", ", selectedMutators),
            StartMap: ReflexArenaModuleCatalog.GetMapLabel(settings.StartMap),
            MapCountLabel: "Single-map startup",
            RotationPreview: supportedMapsPreview.Length == 0
                ? "No stock map metadata available"
                : string.Join(", ", supportedMapsPreview),
            LimitsSummary: limitsSummary,
            AccessLabel: string.IsNullOrWhiteSpace(settings.ServerPassword) ? "Open lobby" : "Password protected",
            RconLabel: string.IsNullOrWhiteSpace(settings.RefPassword) ? "Optional" : "Configured");
    }

    public IReadOnlyDictionary<string, string> GetContainerEnv(string? jsonSettings)
    {
        var settings = ReflexArenaConfigurationSerializer.Deserialize(jsonSettings);
        var env = new Dictionary<string, string>
        {
            ["REFLEX_HOSTNAME"] = settings.Hostname,
            ["REFLEX_MODE"] = settings.Mode,
            ["REFLEX_START_MAP"] = settings.StartMap,
            ["REFLEX_START_MUTATORS"] = string.Join(" ", settings.Mutators),
            ["REFLEX_MAXCLIENTS"] = settings.MaxClients.ToString(),
            ["REFLEX_STEAM"] = settings.SteamEnabled ? "1" : "0",
            ["REFLEX_COUNTRY"] = settings.Country,
            ["REFLEX_TIMELIMIT_OVERRIDE"] = settings.TimeLimitOverride.ToString(),
            ["REFLEX_PASSWORD"] = settings.ServerPassword,
            ["REFLEX_REF_PASSWORD"] = settings.RefPassword,
        };

        var workshopStartMapId = ReflexArenaModuleCatalog.GetWorkshopMapId(settings.StartMap);
        if (!string.IsNullOrWhiteSpace(workshopStartMapId))
        {
            env["REFLEX_START_WORKSHOP_MAP"] = workshopStartMapId;
        }

        if (settings.CustomRules is { Enabled: true } rules)
        {
            env["REFLEX_RULESET_NAME"] = string.IsNullOrWhiteSpace(rules.RulesetName)
                ? "custom" : rules.RulesetName;
            env["REFLEX_RULESET_CONFIG"] = BuildRulesetConfig(rules);
        }

        return env;
    }

    public string CreateDefaultJson() => ReflexArenaSeedConfiguration.CreateDefaultJson();

    private static string BuildRulesetConfig(ReflexArenaCustomRules rules)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// Generated by reflex-arena panel");

        foreach (var w in rules.Weapons)
        {
            sb.AppendLine($"gconst_{w.Key}_enabled {(w.WeaponEnabled ? 1 : 0)}");
            if (!w.WeaponEnabled) continue;

            if (w.DirectDamage.HasValue)
                sb.AppendLine($"gconst_{w.Key}_damage {w.DirectDamage.Value}");
            if (w.SplashDamage.HasValue)
                sb.AppendLine($"gconst_{w.Key}_splashdamage {w.SplashDamage.Value}");
            if (w.InfiniteAmmo)
                sb.AppendLine($"gconst_{w.Key}_maxammo 0");
            else if (w.MaxAmmo.HasValue)
                sb.AppendLine($"gconst_{w.Key}_maxammo {w.MaxAmmo.Value}");
        }

        foreach (var p in rules.Pickups)
        {
            var gconst = ReflexArenaWeaponsCatalog.FindPickup(p.Key)?.Gconst;
            if (!string.IsNullOrWhiteSpace(gconst))
                sb.AppendLine($"{gconst} {(p.Enabled ? 1 : 0)}");
        }

        if (rules.Gravity.HasValue)
            sb.AppendLine($"gconst_gravity {rules.Gravity.Value}");

        return sb.ToString().TrimEnd();
    }
}
