#!/bin/bash
# SPDX-License-Identifier: AGPL-3.0-or-later
# Copyright (C) 2025 Zeus <admin@brainode.com>

set -eu

write_line() {
    key="$1"
    value="$2"
    printf '%s %s\n' "$key" "$(printf '%s' "$value" | tr '\r\n' '  ' | sed 's/[[:space:]]\+$//')"
}

write_optional_line() {
    key="$1"
    value="$2"
    if [ -n "$value" ]; then
        write_line "$key" "$value"
    fi
}

rewrite_default_cfg() {
    file="$1"
    tmp_file="${file}.tmp"

    awk -v mode="$REFLEX_MODE" -v map="$REFLEX_START_MAP" -v mutators="$REFLEX_START_MUTATORS" '
        BEGIN {
            sawMode = 0
            sawMap = 0
            sawWorkshopMap = 0
            sawRotation = 0
            sawMutators = 0
        }
        /^sv_startmode[[:space:]]+/ {
            print "sv_startmode " mode
            sawMode = 1
            next
        }
        /^sv_startmap[[:space:]]+/ {
            print "sv_startmap " map
            sawMap = 1
            next
        }
        /^sv_startwmap[[:space:]]+/ {
            print "sv_startwmap \"\""
            sawWorkshopMap = 1
            next
        }
        /^sv_startrotation[[:space:]]+/ {
            print "sv_startrotation \"\""
            sawRotation = 1
            next
        }
        /^sv_startmutators[[:space:]]+/ || /^\/\/ sv_startmutators[[:space:]]+/ {
            if (length(mutators) > 0) {
                print "sv_startmutators " mutators
            } else {
                print "// sv_startmutators instagib"
            }
            sawMutators = 1
            next
        }
        {
            print
        }
        END {
            if (!sawMode) {
                print "sv_startmode " mode
            }
            if (!sawMap) {
                print "sv_startmap " map
            }
            if (!sawWorkshopMap) {
                print "sv_startwmap \"\""
            }
            if (!sawRotation) {
                print "sv_startrotation \"\""
            }
            if (length(mutators) > 0 && !sawMutators) {
                print "sv_startmutators " mutators
            }
        }
    ' "$file" > "$tmp_file"

    mv "$tmp_file" "$file"
}

REFLEX_INSTALL_DIR="${REFLEX_INSTALL_DIR:-/opt/reflex-arena}"
REFLEX_DATA_DIR="${REFLEX_DATA_DIR:-/var/lib/reflex-arena}"
REFLEX_RUN_USER="${REFLEX_RUN_USER:-reflex}"

REFLEX_HOSTNAME="${REFLEX_HOSTNAME:-Reflex Arena Docker Server}"
REFLEX_MODE="${REFLEX_MODE:-1v1}"
REFLEX_START_MAP="${REFLEX_START_MAP:-Fusion}"
REFLEX_START_MUTATORS="${REFLEX_START_MUTATORS:-}"
REFLEX_MAXCLIENTS="${REFLEX_MAXCLIENTS:-8}"
REFLEX_STEAM="${REFLEX_STEAM:-1}"
REFLEX_ALLOW_EDIT="${REFLEX_ALLOW_EDIT:-0}"
REFLEX_GAME_PORT="${REFLEX_GAME_PORT:-25787}"
REFLEX_COUNTRY="${REFLEX_COUNTRY:-}"
REFLEX_TIMELIMIT_OVERRIDE="${REFLEX_TIMELIMIT_OVERRIDE:-0}"
REFLEX_PASSWORD="${REFLEX_PASSWORD:-}"
REFLEX_REF_PASSWORD="${REFLEX_REF_PASSWORD:-}"
REFLEX_RCON_PASSWORD="${REFLEX_RCON_PASSWORD:-docker-rcon-secret}"
# Map to load first (must exist in base game). rcon switches to REFLEX_START_MAP after boot.
REFLEX_SAFE_MAP="${REFLEX_SAFE_MAP:-Fusion}"
REFLEX_MAP_CHANGE_WAIT="${REFLEX_MAP_CHANGE_WAIT:-12}"

mkdir -p "${REFLEX_DATA_DIR}/logs"
ln -snf "$REFLEX_DATA_DIR" "${REFLEX_INSTALL_DIR}/docker-data"

cat > "${REFLEX_INSTALL_DIR}/dedicatedserver.cfg" << CFG
// Generated by reflex-entrypoint.
CFG

write_line sv_hostname "$REFLEX_HOSTNAME" >> "${REFLEX_INSTALL_DIR}/dedicatedserver.cfg"
write_line sv_startmode "$REFLEX_MODE" >> "${REFLEX_INSTALL_DIR}/dedicatedserver.cfg"
write_line sv_startmap "$REFLEX_START_MAP" >> "${REFLEX_INSTALL_DIR}/dedicatedserver.cfg"
write_line sv_startrotation "" >> "${REFLEX_INSTALL_DIR}/dedicatedserver.cfg"
write_line sv_maxclients "$REFLEX_MAXCLIENTS" >> "${REFLEX_INSTALL_DIR}/dedicatedserver.cfg"
write_line sv_steam "$REFLEX_STEAM" >> "${REFLEX_INSTALL_DIR}/dedicatedserver.cfg"
write_line sv_allowedit "$REFLEX_ALLOW_EDIT" >> "${REFLEX_INSTALL_DIR}/dedicatedserver.cfg"
write_line sv_gameport "$REFLEX_GAME_PORT" >> "${REFLEX_INSTALL_DIR}/dedicatedserver.cfg"
write_line com_logfilename "docker-data/logs/reflexded.log" >> "${REFLEX_INSTALL_DIR}/dedicatedserver.cfg"
write_optional_line sv_country "$REFLEX_COUNTRY" >> "${REFLEX_INSTALL_DIR}/dedicatedserver.cfg"

if [ "$REFLEX_TIMELIMIT_OVERRIDE" != "0" ]; then
    write_line sv_timelimit_override "$REFLEX_TIMELIMIT_OVERRIDE" >> "${REFLEX_INSTALL_DIR}/dedicatedserver.cfg"
fi

write_optional_line sv_startmutators "$REFLEX_START_MUTATORS" >> "${REFLEX_INSTALL_DIR}/dedicatedserver.cfg"
write_optional_line sv_password "$REFLEX_PASSWORD" >> "${REFLEX_INSTALL_DIR}/dedicatedserver.cfg"
write_optional_line sv_refpassword "$REFLEX_REF_PASSWORD" >> "${REFLEX_INSTALL_DIR}/dedicatedserver.cfg"
write_line sv_rconpassword "$REFLEX_RCON_PASSWORD" >> "${REFLEX_INSTALL_DIR}/dedicatedserver.cfg"

# Reflex ships a stock dedicatedserver_default.cfg with sv_startrotation default
# and a workshop map configured. Comment those out in-place so the dedicated
# server falls back to the selected local start map instead of empty/default.
rewrite_default_cfg "${REFLEX_INSTALL_DIR}/dedicatedserver_default.cfg"

printf '[reflex-arena] Mode: %s\n' "$REFLEX_MODE"
printf '[reflex-arena] Start map: %s\n' "$REFLEX_START_MAP"
printf '[reflex-arena] Game port: %s\n' "$REFLEX_GAME_PORT"
printf '[reflex-arena] Mutators: %s\n' "${REFLEX_START_MUTATORS:-none}"

if [ "$(id -u)" = "0" ]; then
    chown -R "${REFLEX_RUN_USER}:${REFLEX_RUN_USER}" "$REFLEX_DATA_DIR" "$REFLEX_INSTALL_DIR"
fi

cd "$REFLEX_INSTALL_DIR"

export HOME="$REFLEX_DATA_DIR"
export USER="$REFLEX_RUN_USER"
export LOGNAME="$REFLEX_RUN_USER"
export LD_LIBRARY_PATH="${REFLEX_INSTALL_DIR}:${REFLEX_INSTALL_DIR}/linux64${LD_LIBRARY_PATH:+:${LD_LIBRARY_PATH}}"

# Start on REFLEX_SAFE_MAP first; after the server is up we rcon-switch to
# REFLEX_START_MAP. This avoids startup failures when the configured map is a
# custom/community map that the engine cannot resolve before full init.
set -- \
    +sv_startrotation "" \
    +sv_startmode "$REFLEX_MODE" \
    +sv_startmap "$REFLEX_SAFE_MAP" \
    "$@"

if [ -n "$REFLEX_START_MUTATORS" ]; then
    set -- +sv_startmutators "$REFLEX_START_MUTATORS" "$@"
fi

if [ "$(id -u)" = "0" ]; then
    gosu "$REFLEX_RUN_USER" env \
        HOME="$REFLEX_DATA_DIR" \
        USER="$REFLEX_RUN_USER" \
        LOGNAME="$REFLEX_RUN_USER" \
        LD_LIBRARY_PATH="$LD_LIBRARY_PATH" \
        "${REFLEX_INSTALL_DIR}/reflexded" "$@" &
else
    "${REFLEX_INSTALL_DIR}/reflexded" "$@" &
fi
SERVER_PID=$!
trap 'kill -TERM "$SERVER_PID" 2>/dev/null; wait "$SERVER_PID"' TERM INT

# If the configured map differs from the safe boot map, wait for the server to
# finish loading then send a Quake-style rcon packet to switch maps.
if [ "$REFLEX_START_MAP" != "$REFLEX_SAFE_MAP" ]; then
    printf '[reflex-arena] Boot map: %s — switching to "%s" in %s s via rcon\n' \
        "$REFLEX_SAFE_MAP" "$REFLEX_START_MAP" "$REFLEX_MAP_CHANGE_WAIT"
    sleep "$REFLEX_MAP_CHANGE_WAIT"
    if kill -0 "$SERVER_PID" 2>/dev/null; then
        printf '\xff\xff\xff\xffrcon %s map %s\n' \
            "$REFLEX_RCON_PASSWORD" "$REFLEX_START_MAP" \
            > /dev/udp/127.0.0.1/"$REFLEX_GAME_PORT" 2>/dev/null \
        && printf '[reflex-arena] rcon sent: map %s\n' "$REFLEX_START_MAP" \
        || printf '[reflex-arena] Warning: rcon send failed\n'
    else
        printf '[reflex-arena] Warning: server exited before rcon map change\n'
    fi
fi

wait "$SERVER_PID"
