#!/bin/sh
# SPDX-License-Identifier: AGPL-3.0-or-later
# Copyright (C) 2025 Zeus <admin@brainode.com>

set -eu

write_line() {
    key="$1"
    value="$2"
    printf '%s %s\n' "$key" "$(printf '%s' "$value" | tr '\r\n' '  ' | sed 's/[[:space:]]\+$//')"
}

write_optional_line() {
    key="$1"
    value="$2"
    if [ -n "$value" ]; then
        write_line "$key" "$value"
    fi
}

rewrite_default_cfg() {
    file="$1"
    tmp_file="${file}.tmp"

    awk -v mode="$REFLEX_MODE" -v map="$REFLEX_START_MAP" -v mutators="$REFLEX_START_MUTATORS" '
        BEGIN {
            sawMode = 0
            sawMap = 0
            sawWorkshopMap = 0
            sawMutators = 0
        }
        /^sv_startmode[[:space:]]+/ {
            print "sv_startmode " mode
            sawMode = 1
            next
        }
        /^sv_startmap[[:space:]]+/ {
            print "sv_startmap " map
            sawMap = 1
            next
        }
        /^sv_startwmap[[:space:]]+/ {
            print "sv_startwmap \"\""
            sawWorkshopMap = 1
            next
        }
        /^sv_startrotation[[:space:]]+/ {
            next
        }
        /^sv_startmutators[[:space:]]+/ || /^\/\/ sv_startmutators[[:space:]]+/ {
            if (length(mutators) > 0) {
                print "sv_startmutators " mutators
            } else {
                print "// sv_startmutators instagib"
            }
            sawMutators = 1
            next
        }
        {
            print
        }
        END {
            if (!sawMode) {
                print "sv_startmode " mode
            }
            if (!sawMap) {
                print "sv_startmap " map
            }
            if (!sawWorkshopMap) {
                print "sv_startwmap \"\""
            }
            if (length(mutators) > 0 && !sawMutators) {
                print "sv_startmutators " mutators
            }
        }
    ' "$file" > "$tmp_file"

    mv "$tmp_file" "$file"
}

REFLEX_INSTALL_DIR="${REFLEX_INSTALL_DIR:-/opt/reflex-arena}"
REFLEX_DATA_DIR="${REFLEX_DATA_DIR:-/var/lib/reflex-arena}"
REFLEX_RUN_USER="${REFLEX_RUN_USER:-reflex}"

REFLEX_HOSTNAME="${REFLEX_HOSTNAME:-Reflex Arena Docker Server}"
REFLEX_MODE="${REFLEX_MODE:-1v1}"
REFLEX_START_MAP="${REFLEX_START_MAP:-Fusion}"
REFLEX_START_MUTATORS="${REFLEX_START_MUTATORS:-}"
REFLEX_MAXCLIENTS="${REFLEX_MAXCLIENTS:-8}"
REFLEX_STEAM="${REFLEX_STEAM:-1}"
REFLEX_ALLOW_EDIT="${REFLEX_ALLOW_EDIT:-0}"
REFLEX_GAME_PORT="${REFLEX_GAME_PORT:-25787}"
REFLEX_COUNTRY="${REFLEX_COUNTRY:-}"
REFLEX_TIMELIMIT_OVERRIDE="${REFLEX_TIMELIMIT_OVERRIDE:-0}"
REFLEX_PASSWORD="${REFLEX_PASSWORD:-}"
REFLEX_REF_PASSWORD="${REFLEX_REF_PASSWORD:-}"

mkdir -p "${REFLEX_DATA_DIR}/logs"
ln -snf "$REFLEX_DATA_DIR" "${REFLEX_INSTALL_DIR}/docker-data"

cat > "${REFLEX_INSTALL_DIR}/dedicatedserver.cfg" << CFG
// Generated by reflex-entrypoint.
CFG

write_line sv_hostname "$REFLEX_HOSTNAME" >> "${REFLEX_INSTALL_DIR}/dedicatedserver.cfg"
write_line sv_startmode "$REFLEX_MODE" >> "${REFLEX_INSTALL_DIR}/dedicatedserver.cfg"
write_line sv_startmap "$REFLEX_START_MAP" >> "${REFLEX_INSTALL_DIR}/dedicatedserver.cfg"
write_line sv_maxclients "$REFLEX_MAXCLIENTS" >> "${REFLEX_INSTALL_DIR}/dedicatedserver.cfg"
write_line sv_steam "$REFLEX_STEAM" >> "${REFLEX_INSTALL_DIR}/dedicatedserver.cfg"
write_line sv_allowedit "$REFLEX_ALLOW_EDIT" >> "${REFLEX_INSTALL_DIR}/dedicatedserver.cfg"
write_line sv_gameport "$REFLEX_GAME_PORT" >> "${REFLEX_INSTALL_DIR}/dedicatedserver.cfg"
write_line com_logfilename "docker-data/logs/reflexded.log" >> "${REFLEX_INSTALL_DIR}/dedicatedserver.cfg"
write_optional_line sv_country "$REFLEX_COUNTRY" >> "${REFLEX_INSTALL_DIR}/dedicatedserver.cfg"

if [ "$REFLEX_TIMELIMIT_OVERRIDE" != "0" ]; then
    write_line sv_timelimit_override "$REFLEX_TIMELIMIT_OVERRIDE" >> "${REFLEX_INSTALL_DIR}/dedicatedserver.cfg"
fi

write_optional_line sv_startmutators "$REFLEX_START_MUTATORS" >> "${REFLEX_INSTALL_DIR}/dedicatedserver.cfg"
write_optional_line sv_password "$REFLEX_PASSWORD" >> "${REFLEX_INSTALL_DIR}/dedicatedserver.cfg"
write_optional_line sv_refpassword "$REFLEX_REF_PASSWORD" >> "${REFLEX_INSTALL_DIR}/dedicatedserver.cfg"

# Reflex ships stock startup workshop/rotation defaults in dedicatedserver_default.cfg.
# Strip them so we can isolate startup behavior to the selected mode/map pair.
rewrite_default_cfg "${REFLEX_INSTALL_DIR}/dedicatedserver_default.cfg"

printf '[reflex-arena] Mode: %s\n' "$REFLEX_MODE"
printf '[reflex-arena] Start map: %s\n' "$REFLEX_START_MAP"
printf '[reflex-arena] Game port: %s\n' "$REFLEX_GAME_PORT"
printf '[reflex-arena] Mutators: %s\n' "${REFLEX_START_MUTATORS:-none}"

if [ "$(id -u)" = "0" ]; then
    chown -R "${REFLEX_RUN_USER}:${REFLEX_RUN_USER}" "$REFLEX_DATA_DIR" "$REFLEX_INSTALL_DIR"
fi

cd "$REFLEX_INSTALL_DIR"

export HOME="$REFLEX_DATA_DIR"
export USER="$REFLEX_RUN_USER"
export LOGNAME="$REFLEX_RUN_USER"
export LD_LIBRARY_PATH="${REFLEX_INSTALL_DIR}:${REFLEX_INSTALL_DIR}/linux64${LD_LIBRARY_PATH:+:${LD_LIBRARY_PATH}}"

set -- \
    +sv_startmode "$REFLEX_MODE" \
    +sv_startmap "$REFLEX_START_MAP" \
    "$@"

if [ -n "$REFLEX_START_MUTATORS" ]; then
    set -- +sv_startmutators "$REFLEX_START_MUTATORS" "$@"
fi

if [ "$(id -u)" = "0" ]; then
    exec gosu "$REFLEX_RUN_USER" env \
        HOME="$REFLEX_DATA_DIR" \
        USER="$REFLEX_RUN_USER" \
        LOGNAME="$REFLEX_RUN_USER" \
        LD_LIBRARY_PATH="$LD_LIBRARY_PATH" \
        "${REFLEX_INSTALL_DIR}/reflexded" "$@"
fi

exec "${REFLEX_INSTALL_DIR}/reflexded" "$@"
