#!/bin/sh
set -eu

QL_INSTALL_DIR="${QL_INSTALL_DIR:-/opt/quake-live}"
QL_HOME_DIR="${QL_HOME_DIR:-/var/lib/quake-live}"
QL_RUNTIME_ARCH="${QL_RUNTIME_ARCH:-x86}"
QL_RUN_USER="${QL_RUN_USER:-quakelive}"

QL_HOSTNAME="${QL_HOSTNAME:-Quake Live Standalone Test}"
QL_FACTORY="${QL_FACTORY:-duel}"
QL_MAPLIST="${QL_MAPLIST:-asylum brimstoneabbey campgrounds purgatory theedge}"
QL_MAXCLIENTS="${QL_MAXCLIENTS:-16}"
QL_SERVER_TYPE="${QL_SERVER_TYPE:-2}"
QL_PASSWORD="${QL_PASSWORD:-}"
QL_TAGS="${QL_TAGS:-standalone}"
QL_IDLE_EXIT="${QL_IDLE_EXIT:-0}"
QL_NET_IP="${QL_NET_IP:-0.0.0.0}"
QL_NET_PORT="${QL_NET_PORT:-27960}"
QL_ZMQ_RCON_ENABLE="${QL_ZMQ_RCON_ENABLE:-0}"
QL_ZMQ_RCON_PORT="${QL_ZMQ_RCON_PORT:-28960}"
QL_ZMQ_RCON_PASSWORD="${QL_ZMQ_RCON_PASSWORD:-}"
QL_ZMQ_STATS_ENABLE="${QL_ZMQ_STATS_ENABLE:-0}"
QL_ZMQ_STATS_PORT="${QL_ZMQ_STATS_PORT:-27960}"
QL_ZMQ_STATS_PASSWORD="${QL_ZMQ_STATS_PASSWORD:-}"
QL_SV_FPS="${QL_SV_FPS:-120}"
QL_SV_PPS="${QL_SV_PPS:-80}"

BASEQ3_DIR="${QL_HOME_DIR}/baseq3"
STEAM_HOME_DIR="${QL_HOME_DIR}/.steam"
mkdir -p "$BASEQ3_DIR" "${STEAM_HOME_DIR}/sdk32" "${STEAM_HOME_DIR}/sdk64"

ln -snf "${QL_INSTALL_DIR}/steamclient.so" "${STEAM_HOME_DIR}/sdk32/steamclient.so"
ln -snf "${QL_INSTALL_DIR}/linux64/steamclient.so" "${STEAM_HOME_DIR}/sdk64/steamclient.so"

rm -f "${BASEQ3_DIR}/profile.pid"

# Write a clean server.cfg on every startup — no accumulating duplicates.
cat > "${BASEQ3_DIR}/server.cfg" << CFG
// Generated by ql-entrypoint — overwritten on each startup.
set sv_hostname "${QL_HOSTNAME}"
set sv_maxclients "${QL_MAXCLIENTS}"
set sv_serverType "${QL_SERVER_TYPE}"
set sv_master "1"
set g_password "${QL_PASSWORD}"
set sv_tags "${QL_TAGS}"
set g_accessFile "access.txt"
set g_voteFlags "0"
set g_allowVote "1"
set com_hunkMegs "60"
set sv_floodprotect "10"
set zmq_rcon_enable "${QL_ZMQ_RCON_ENABLE}"
set zmq_rcon_port "${QL_ZMQ_RCON_PORT}"
set zmq_rcon_password "${QL_ZMQ_RCON_PASSWORD}"
set zmq_stats_enable "${QL_ZMQ_STATS_ENABLE}"
set zmq_stats_port "${QL_ZMQ_STATS_PORT}"
set zmq_stats_password "${QL_ZMQ_STATS_PASSWORD}"
set sv_fps "${QL_SV_FPS}"
set sv_pps "${QL_SV_PPS}"
set sv_idleExit "${QL_IDLE_EXIT}"
set sv_mapPoolFile "mappool.txt"
set serverstartup "startRandomMap"
CFG

{
    for map in $QL_MAPLIST; do
        printf '%s|%s\n' "$map" "$QL_FACTORY"
    done
} > "${BASEQ3_DIR}/mappool.txt"

RUN_SCRIPT="${QL_INSTALL_DIR}/run_server_${QL_RUNTIME_ARCH}.sh"
if [ ! -x "$RUN_SCRIPT" ]; then
    printf '[ql-standalone] Unsupported runtime arch: %s\n' "$QL_RUNTIME_ARCH" >&2
    exit 1
fi

printf '[ql-standalone] Home: %s\n' "$QL_HOME_DIR"
printf '[ql-standalone] Runtime: %s\n' "$QL_RUNTIME_ARCH"
printf '[ql-standalone] Maps: %s\n' "$QL_MAPLIST"
printf '[ql-standalone] Port: %s\n' "$QL_NET_PORT"

if [ "$(id -u)" = "0" ]; then
    chown -R "${QL_RUN_USER}:${QL_RUN_USER}" "$QL_HOME_DIR"
fi

cd "$QL_INSTALL_DIR"

export HOME="$QL_HOME_DIR"
export USER="$QL_RUN_USER"
export LOGNAME="$QL_RUN_USER"

set -- \
    "$RUN_SCRIPT" \
    +set net_strict 1 \
    +set fs_homepath "$QL_HOME_DIR" \
    +set net_ip "$QL_NET_IP" \
    +set net_port "$QL_NET_PORT" \
    +exec server.cfg \
    "$@"

if [ "$(id -u)" = "0" ]; then
    exec gosu "$QL_RUN_USER" env \
        HOME="$QL_HOME_DIR" \
        USER="$QL_RUN_USER" \
        LOGNAME="$QL_RUN_USER" \
        "$@"
fi

exec "$@"
